services:
  # Django Web Service
  - type: web
    name: realtime-dashboard
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn dashboard_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: realtime_dashboard
      - key: ALLOWED_HOSTS
        sync: false
